### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_AppState$addEventLis.remove')

### ISSUE THREAD

**Issue by saeedtkh** [a7med-mahmoud/react-native-prevent-screenshots#2]
Hello, thanks for the component that you developed. I am getting this error when I run the app:

`TypeError: undefined is not an object (evaluating '_AppState$addEventLis.remove')`

I warped my app.js using export default withPreventScreenshots(App) and then receive the error.
react native 64.0.1
platform iOS

Can you please help me?

**Comment by a7medev** [comment]
I think I detected the problem, I'll be working on it today.

**Comment by a7medev** [comment]
Solved the issue in [v1.1.0](https://github.com/a7med-mahmoud/react-native-prevent-screenshots/releases/tag/1.1.0), you can update the package to get it fixed.

**Comment by saeedtkh** [comment]
@a7med-mahmoud : Thank you very much for your time and speed. We really appreciate you, but I updated the package and I am seeing the same error with v1.1.0.

**Comment by a7medev** [comment]
Thanks for the feedback, I tried the package again and it's working perfectly with React Native 0.64. Please make sure the package is updated properly and try [clearing the React Native/Metro cache](https://stackoverflow.com/questions/46878638/how-to-clear-react-native-cache).

**Comment by saeedtkh** [comment]
@a7med-mahmoud : Thank you I tried it, this time there is no error, but I can get screen shots on iOS simulator device. by the way is working with simulator or I should use a real device?

**Comment by a7medev** [comment]
You have to use a real device as the Simulator's screenshot feature is not the same as a on-device screenshot
